### ISSUE TITLE
Finish creation of Fine Narrative

### ISSUE THREAD

**Issue by joshkyh** [SpectData/MONAH#13]
In progress to build Fine Narrative: Nodding, Forward Trunk Leaning.

**Comment by joshkyh** [comment]
Head nodding ready for Thur demo. Also working on commenting the code.

**Comment by joshkyh** [comment]
Demo failed at Line 285 of narrative_fine.py please check.

(1) Time starting from, deleting everything in step.
(2) Time the portion taken by head nodding.

**Comment by mfmakahiya** [comment]
Stage 1 Time:  0:08:42.073105
Stage 2 Prosody SpeechRate Time:  0:00:00.021638
Stage 2 Prosody Delay Time:  0:00:00.100341
Stage 2 Prosody Time:  0:00:00.639074
Stage 2 Action Smile Time:  0:00:02.353334
Stage 2 Action Posiface Time:  0:00:04.316208
Stage 2 Action AUs Time:  0:00:04.179329
Stage 2 Action HeadNod Time:  0:01:20.589899
Stage 2 Action ForwardLean Time:  0:00:04.134147
Stage 2 Action Time:  0:01:35.641939
Done data processing - Stage 2
Stage 2 Time:  0:01:36.281013
Done data processing - Stage 3
Stage 3 Time:  0:00:00.597681
All Stages Run Time:  0:10:18.951799

**Comment by joshkyh** [comment]
Fine narratives done.
