### ISSUE TITLE
Bug - M/F in Talkturn No. Column

### ISSUE THREAD

**Issue by joshkyh** [SpectData/MONAH#22]
Hi Marriane,

Suppose I sidestepped the issue in the #21 ; in tfp.combine_prosody_features, I ran into another problem at dfr = pd.merge(dfr, df_, how='outer', on=['audio_id', 'speaker', 'talkturn no'])

See below screenshot
![image](https://user-images.githubusercontent.com/14764966/107465501-98666780-6bb6-11eb-92a2-1509d0c417d1.png)

Why do I see M/F in talkturn number when it should be integers..?

**Comment by joshkyh** [comment]
df_vokaturi in line #76 of talktun_family_prosody has broken talkturn no column.

This is due to bad talkturn_vokaturi.csv which is created in line #123 of execute_vokaturi.py

We suspect that it is due to the hardcoding of underscore positions, whihc is risky given that we don't know what underscore naming convention will be in user supplied files.

**Comment by mfmakahiya** [comment]
Hi Joshua! I have fixed the issue with the talkturn number without hardcoding underscore positions.

**Comment by joshkyh** [comment]
That is great @mfmakahiya , could you please follow through to try run lines 183 and 184 of 
https://github.com/SpectData/MONAH/blob/dev-pitch/Python/Data_Exploration/rescore_all_iemocap_pitchvol.py
to see that there is no further error?

**Comment by mfmakahiya** [comment]
Hi Joshua! I'm just having some difficulty with the azure storage blob. I can't seem to import the BlobServiceClient package.

**Comment by joshkyh** [comment]
Let's migrate to Linux, please recreate the MONAH environment using Linux.yml. That would save us trouble in the long run.

**Comment by joshkyh** [comment]
Done with 25a40e4
