### ISSUE TITLE
Preparation of video clips for user study

### ISSUE THREAD

**Issue by joshkyh** [SpectData/MONAH#23]
1) Download openshot https://www.openshot.org/download/
2) Change your open shot profile to 
![image](https://user-images.githubusercontent.com/14764966/108822427-2e68ac00-7613-11eb-9e30-e268ffbce886.png)

3) Cut the 3 talkturns out as indicated in the [Choose Questions] Tab

4) Ensure that the first talkturn starts when the other speaker finished talking (so that we capture the delay). The last talkturn can end immeiately after its speaker stop its last word.

5) Export video with the same name, but under a subfolder called precise3. Colour the cells blue so that I can double check

**Comment by mfmakahiya** [comment]
All done with this. Files are already uploaded in precise3 folder.

**Comment by joshkyh** [comment]
Hi @mfmakahiya great work thank you!

I have gone through all the video clips and have a handful of clips that require a more precise editing. I have highlighted the talk turns that require work in yellow, and my comments beside it. Did you know that you could zoom in the time scale to get a more precise trimming? :)

Please color them in blue when you're done and I'll go through a second pass.

Thanks again! :D

Joshua

**Comment by mfmakahiya** [comment]
Hi Joshua! I have updated the clips needed to be fixed. Thanks!

**Comment by joshkyh** [comment]
HI @mfmakahiya Thank you, great work. I will now move onto providing you the next 8 video snippets (2 training examples x 4 emotions) in the Excel to be used in the Training phase. I'll brief you over our meeting :)
