### ISSUE TITLE
Build the Qualtrics Survey

### ISSUE THREAD

**Issue by joshkyh** [SpectData/MONAH#24]
Joshua to go through the survey design and record it on Teams.

**Comment by joshkyh** [comment]
(1) Please italics the content within parentheses.
(2) Uppercase the relevant words, remove double spaces and add apostrophe.
(3) First letter of the talkturns should be capitalized.
(4) Chronemics/ Kinesics and Paralinguistics, put back the long description in the question.
(5) Check that every question in part 1 (guess the emotion) has a hidden timer.
(6) Random two attempts at the entire survey and export the result to see if we can analyse it.
(7) Training phase videos.

**Comment by joshkyh** [comment]
1. Indicate in brackets the speaker for the third talkturn for video questions.
2. Change screen to without grid
3. Export results in csv, pivot it in R to see if you can analyze it. See if timings are captured and it is easy to analyze.

**Comment by joshkyh** [comment]
Joshua's Quality Check:
1. Q148, Q7 MNJVT block Should it be:
[Jefferson]

((the   man said)) what  you seem so excited.
((the   woman smiled the woman said)) its really exciting  dont you want to guess.
((the   man said)) uh you got a new car a new house uh a dog.



2. Q149, Q8 MNJVT block Should it be:
[Jefferson]
((the woman smiled the woman said))   well im very sorry sir  they should   have dealt with it at that particular branch    i apologize for that uh but we can help you  thats no worries  we can take care of that  so how much did you need to be refunded.
((the man said)) it was a hundred a   sixty dollars  im sorry uh sixteen   dollars.
((the   woman smiled the woman said)) okay  um   im going to go ahead and transfer you over to another department  theyll need your address.

3. Q150, Q9 MNJVT block should it be:
[Jefferson]
((the   man smiled the man said)) yeah i dont know    but yeah so anyway  well i   wanted to tell you that you know cause youre one of my good friends and youre   kates one of her best friends and.
--
((the   woman smiled the woman said)) im so excited for you thats great im so.
((the   man smiled the man said)) yeah yeah she was actually  she was going to tell you but i told her   that i wanted to tell you and she had to work today anyway so i decided to.

**Comment by joshkyh** [comment]
Joshua's Quality Check:
NJVTM

Q157, Q1: Order of talkturns is inverted in MONAH+

Q160, Q4: Jefferson content should be Ses02M script01_2
Q161, Q5: Jefferson content should be Ses04M impro05
Q162, Q6: Jefferson content should be Ses05F impro03

Q165, Q9: Please provide YouTube link to Ses04M, impro3.

**Comment by joshkyh** [comment]
Joshua's Quality Check JVTMN:

Q172, Q1: Jefferson for Ses02F, impro02
Q173, Q2: Jefferson for Ses01F impro01
Q174, Q3: Jefferson for Ses02M, impro02

Q184, Q13 MONAH+ Missing
Q185, Q14 MONAH+ Missing
Q186, Q15 MONAH+ Missing
Q17 MONAH+ Missing
Q20 MONAH+ Missing
Q23 MONAH+ Missing

**Comment by joshkyh** [comment]
Joshua's Quality Check VTMNJ:

Q10 MONAH+ Missing
Q11 MONAH+ Missing
Q12 MONAH+ Missing

Q13 Jefferson for Ses05M script01_3
Q14 Jefferson for Ses05M impro08
Q15 Jefferson for Ses04M script01_1

Q17 MONAH+ Missing
Q20 MONAH+ Missing
Q23 MONAH+ Missing

**Comment by joshkyh** [comment]
Rate system:

Q214 Add an example for MONAH, MONAH+ and Jefferson. We can use the training examples, it is only to quick-refresh the participants' memory.

**Comment by mfmakahiya** [comment]
Regarding Jefferson, yeah. They are not updated as we are still waiting for the actual transcripts.

For the others, I'm still in the middle of putting the rest of the MONAH+ photos. Thanks!

**Comment by mfmakahiya** [comment]
Hi Joshua! I have already pasted the youtube links and video duration (in seconds) in the google sheet file. Column M as the youtube link and column N as the video duration. Thanks!

**Comment by joshkyh** [comment]
Done
